In [71]:
import pandas as pd
import numpy as np


color = ["red","green","red","blue","green"]
weather = ["sunny","cloudy","cloudy","rainy","sunny"]
education = ["L","H","H","H","L"]
test = ["P","N","P","N","P"]
location = ["(1,8)","(3,4)","(5,7)","(6,2)","(9,10)"]
grade = ["fair","good","excellent","good","fair"]

df = pd.DataFrame({"Color": color,
                   "Weather": weather,
                   "Education": education,
                   "Test": test,
                   "Location": location,
                   "Grade": grade
                  })
df.head()
df.columns

Index(['Color', 'Weather', 'Education', 'Test', 'Location', 'Grade'], dtype='object')

In [ ]:
# -*- coding: utf-8 -*-
# SIE 433/533 HW2 Problem 1

def get_proxi_mtx(attribute, X):
    """
    Generate a proximity matrix for different types of data
    type: the attribute of the input data
    X: data input array
    proxi: output matrix
    """
    attribute = X.columns
# check the type
    if type == "Nominal":
        #using the formula in page 7 of Lecture 5
        proxi = 
        
    if type == "Binary":
        #using the formula in page 9 of Lecture 5
        proxi = 
        
    if type == "Numeric":
        #using the Euclidean distance in page 13 of Lecture 5
        proxi = 
        
    
    if type == "Ordinal":
        #using the formula in page 16 of Lecture 5
        proxi = 
        
    
    if type == "Mixed":
        #using the formula in page 18 of Lecture 5
        proxi = 
    
    return proxi

In [98]:
# p = total number of attributes; m = number of matched attributes
# d_i_j = (p-m)/p
import itertools
nominal_df = df[["Color", "Weather"]]
p = len(nominal_df.columns)
obj_1 = nominal_df.iloc[[0]]
obj_2 = nominal_df.iloc[[1]]
obj_3 = nominal_df.iloc[[2]]
obj_4 = nominal_df.iloc[[3]]
obj_5 = nominal_df.iloc[[4]]

objects = [obj_1,obj_2,obj_3,obj_4,obj_5]
objects2 = [obj_1,obj_2,obj_3,obj_4,obj_5]

def get_matches(a, b):
    matched = 0
    if a.iloc[0]["Color"] == b.iloc[0]["Color"]:
        matched += 1
        print("hit first")
    if a.iloc[0]["Weather"] == b.iloc[0]["Weather"]:
        matched += 1
        print("hit second")
    return matched
print("Matches:", get_matches(obj_2, obj_3))
get_matches(obj_2, obj_3)

def prox_nominal(n, m):
    return (p-get_matches(n,m))/p

# print(prox_nominal(obj_1))
# print(prox_nominal(obj_2,obj_3))

# final_matrix = []
def do_the_thing():
    final_matrix = []
    for x in objects:
        for y in objects2:
            final_matrix.append(prox_nominal(x,y))
    return final_matrix

            
# Asymmetric Proximity Measure for Binary Attributes
#  d(i,j) = (m10 + m01)/(m11 + m10 + m01)

"""Uncomment below later"""
do_the_thing()
print(len(do_the_thing()))
print(final_matrix)
final_matrix = np.reshape(final_matrix, (5,5))
print(final_matrix)

nominal_df.head()

hit second
Matches: 1
hit second
hit first
hit second
hit first
hit second
hit first
hit second
hit second
hit first
hit first
hit second
hit first
hit second
hit first
hit second
hit second
hit first
hit first
hit second
hit first
hit second
hit first
hit second
hit first
hit second
hit second
hit first
hit first
hit second
hit first
hit second
hit first
hit second
hit second
hit first
hit first
hit second
25
[[0.  1.  0.5 1.  0.5]
 [1.  0.  0.5 1.  0.5]
 [0.5 0.5 0.  1.  1. ]
 [1.  1.  1.  0.  1. ]
 [0.5 0.5 1.  1.  0. ]]
[[0.  1.  0.5 1.  0.5]
 [1.  0.  0.5 1.  0.5]
 [0.5 0.5 0.  1.  1. ]
 [1.  1.  1.  0.  1. ]
 [0.5 0.5 1.  1.  0. ]]


Color Weather
0    red   sunny
1  green  cloudy
2    red  cloudy
3   blue   rainy
4  green   sunny

In [100]:
# Asymmetric Proximity Measure for Binary Attributes
#  d(i,j) = (m10 + m01)/(m11 + m10 + m01)

asym_bin_df = df[["Education", "Test"]]
conversion_dict = {"L": 1,"H":0,"P":1,"N":0}
asym_bin_df["Education"] = df["Education"].map(conversion_dict)
asym_bin_df["Test"] = df["Test"].map(conversion_dict)
asym_bin_df.head()
obj_1 = asym_bin_df.iloc[[0]]
obj_2 = asym_bin_df.iloc[[1]]
obj_3 = asym_bin_df.iloc[[2]]
obj_4 = asym_bin_df.iloc[[3]]
obj_5 = asym_bin_df.iloc[[4]]


def compare(a,b):
    x,y =  a.iloc[0]["Education"], b.iloc[0]["Education"]
    print(x,y)
compare(obj_1, obj_2)

1 0


//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [79]:
# Question 2
x = [0,2,0,0,0,6,0,3,0,0]
y = [3,0,0,0,1,0,0,4,0,2]

def magnitude(vector):
    squared = []
    for a in vector:
        a = a**2
        squared.append(a)
    return sum(squared)**0.5

def dot_product(vec_1, vec_2):
    dp = []
    for i in range(0, len(vec_1)):
        z = vec_1[i] * vec_2[i]
        dp.append(z)
    return sum(dp)

cosine_similarity = dot_product(x,y)/(magnitude(x) * magnitude(y))

print(cosine_similarity)
# To check the above implemtation, I used scipy module
from scipy import spatial

cos_sim = 1 - spatial.distance.cosine(x,y)
print(cos_sim)

0.31298431857438064
0.3129843185743806


0.3129843185743806


In [92]:
import numpy as np
# Use the min-max and z-score normalization to transform the data below:
A = [0.5152, 8.6806, 5.2893, -2.0385, 7.4494, 13.2321, 8.7511, 11.9218, 19.5940, 6.8857]
print(len(A))

# max-min normalization
def minmax_norm(vector):
    answer = []
    vector.sort()
    for num in vector:
        answer.append((num - min(vector))/(max(vector)-min(vector)))
    return answer

rounded = np.round(minmax_norm(A),4)
print("MinMax Normalization: ", rounded)

# Z-Score Normalization
def z_score(vector):
    answer = []
    vector.sort()
    for num in vector:
        answer.append((num - np.mean(vector))/np.std(vector))
    return answer

z_round = np.round(z_score(A),4)
print("Z-Score Normalization: ", z_round)


10
MinMax Normalization:  [0.     0.118  0.3387 0.4125 0.4386 0.4955 0.4988 0.6453 0.7059 1.    ]
Z-Score Normalization:  [-1.7166 -1.2812 -0.467  -0.1948 -0.0987  0.1113  0.1233  0.664   0.8874
  1.9723]
